// AUTO-GENERATED by scripts/build-data.mjs — do not edit by hand.
export const site = {
  "company": {
    "name": "Wilder Belize Adventures",
    "shortName": "Wilder Belize",
    "slogan": "Explore Belize, the Wilder Way",
    "tagline": "Your Gateway to Epic Belize Experiences",
    "phones": [
      "+501 650-1003",
      "+501 671-8828"
    ],
    "whatsapp": "5016501003",
    "emails": [
      "info@wilderbelizeadventures.com",
      "wilderbelizeadventures@gmail.com"
    ],
    "address": "Placencia Village, Stann Creek District, Belize",
    "socials": {
      "facebook": "https://www.facebook.com/wilderbelizeadventures",
      "instagram": "https://www.instagram.com/wilderbelizeadventures",
      "whatsapp": "https://wa.me/5016501003",
      "tripadvisor": "https://www.tripadvisor.com/Attraction_Review-g291977-d25566275-Reviews-Wilder_Belize_Adventures-Placencia_Stann_Creek.html"
    }
  },
  "hero": {
    "kicker": "Placencia Village, Belize",
    "headline": "Explore Belize, the Wilder Way",
    "subheadline": "From jungle waterfalls and Maya temples to the warm Caribbean,  Wilder Belize Adventures takes you deep into the real Belize.",
    "ctaPrimary": "Browse Adventures",
    "ctaSecondary": "Talk to a Guide"
  },
  "valueProps": [
    {
      "icon": "users",
      "title": "Born-and-Raised Guides",
      "detail": "Every trip is led by a Belizean who grew up reading these rivers, ridges, and reefs."
    },
    {
      "icon": "compass",
      "title": "Off the Beaten Trail",
      "detail": "We take you past the postcard stops to the waterfalls, caves, and creeks the buses never reach."
    },
    {
      "icon": "shield",
      "title": "Safety Without the Fuss",
      "detail": "Well-kept gear, small groups, and guides trained in wilderness first response keep the wild fun, not risky."
    },
    {
      "icon": "leaf",
      "title": "Easy on the Wild",
      "detail": "We run low-impact trips that protect the jungle, the reef, and the Maya sites we love to share."
    }
  ],
  "whyChooseUs": [
    {
      "title": "We Actually Live Here",
      "detail": "Wilder is run from Placencia by a Belizean family, not booked through a faraway call center, so you get straight answers and real local know-how."
    },
    {
      "title": "Premium exclusive groups",
      "detail": "We cap our trips so your guide can slow down for the toucan in the canopy or the story behind a Maya glyph instead of herding a crowd."
    },
    {
      "title": "One Outfitter, Whole Country",
      "detail": "Jungle ATV at Mayan King, the Cockscomb jaguar trails, ATM cave, Tikal across the border in Guatemala. Build a week with us and we handle the logistics."
    },
    {
      "title": "Guides Who Host and Entertain",
      "detail": "Our team names the birds, reads the tracks, and explains the history, so you leave understanding Belize, not just having seen it."
    }
  ],
  "aboutShort": "Wilder Belize adventures is a Belizean owned premium tour company, sending travelers into the waterfalls, jungle, and Maya country of southern Belize. Our born-and-raised guides turn a day trip into the kind of story you tell for a lifetime.",
  "aboutLong": "Wilder Belize Adventures is a locally owned and proudly Belizean tour company based in Placencia Village. Since 2023, we've been curating private, eco-friendly tours that blend adventure, culture, and nature. From exploring ancient Maya ruins and lush rainforests to experiencing authentic local traditions and vibrant wildlife, every tour is designed around your pace, your interests, and your sense of adventure. With passionate local guides and a personal touch, we turn every journey into a lifelong memory.\n\nToday we run the trips we'd want our own friends on. A jungle ATV ride to the cascades at Mayan King, where you cool off in the spray after conquering the trail. A trek through the Cockscomb Basin, the world's first jaguar reserve, listening for howler monkeys in the canopy. The slow river glide into Monkey River, the climb up Xunantunich for the view across the valley, the headlamp-lit wade into ATM cave past Maya pottery and the bones of ancient ceremonies. When you want to cross into Guatemala, we'll get you to the great temples of Tikal and back.\n\nWhat ties it together is the people leading you. Our guides were raised on these landscapes, certified for the wild places they take you, and genuinely glad to share them. They'll name the bird before you can lift your camera, read a jaguar track in the mud, and have the cooler stocked for the ride home. That's the Wilder way: real Belize, real Belizeans, and the kind of adventure you don't get from a brochure.",
  "stats": [
  ],
  "testimonials": [
    {
      "name": "riverafm",
      "location": "Humble, Texas",
      "rating": 5,
      "text": "Outstanding tour experience! Our guide was knowledgeable, engaging, and passionate about Belize’s history, wildlife, and",
      "tour": "Xunantunich and Cave Tubing",
      "link": "https://www.tripadvisor.in/ShowUserReviews-g291977-d25566275-r1064589313-Wilder_Belize_Adventures-Placencia_Placencia_Peninsula_Stann_Creek.html"
    },
    {
      "name": "Culture250175",
      "location": "Minneapolis, Minnesota",
      "rating": 5,
      "text": "Best tour of our trip. I can’t say enough about our tour guide, Wilder. He made the trip fun and was incredibly knowledgeable and friendly, making us all feel welcome.",
      "tour": "Xunantunich and Cave Tubing",
      "link": "https://www.tripadvisor.in/ShowUserReviews-g291977-d25566275-r1057841432-Wilder_Belize_Adventures-Placencia_Placencia_Peninsula_Stann_Creek.html"
    },
    {
      "name": "Michaela S",
      "location": "Hanover, Minnesota",
      "rating": 5,
      "text": "Beyond thrilled with our experience Wilder goes above and beyond to make sure everyone is having a good time extremely professional knowledgeable and has so many interesting stories",
      "tour": "ATM Caves Exploration from Placencia",
      "link": "https://www.tripadvisor.in/Profile/msnickers"
    },
    {
      "name": "Jasmine",
      "location": "San Jose, California",
      "rating": 5,
      "text": "We did the water fall tour and it was AMAZING!!! wilder told us all about the birds we saw on our way to the waterfall, the hike was really nice and the waterfall was STUNNING, the water felt really nice especially after the hike. Wilder made sure everything was taken care of the entire time. Thank you Wilder the greatest experience in Belize!!!",
      "tour": " Nim Li Punit + Chocolate + Waterfall from Placencia",
      "link": "https://www.tripadvisor.com/Attraction_Review-g291977-d25566275-Reviews-Wilder_Belize_Adventures-Placencia_Placencia_Peninsula_Stann_Creek.html"
    },
    {
      "name": "Veronica C",
      "location": "Verified Traveler",
      "rating": 5,
      "text": "We had a wonderful experience while visiting Belize. We decided on horseback riding and river tubing. Wilder was so professional and down to earth. The conversation and history shared during the ride was a bonus. We had a great time at both locations and lunch was great. He ordered ahead and we were able to try different items from the menu. Highly recommend booking an experience with him and his team!",
      "tour": "Tour to Horseback Riding & Cave Tubing Adventure from Placencia",
      "link": "https://www.tripadvisor.com/Attraction_Review-g291977-d25566275-Reviews-Wilder_Belize_Adventures-Placencia_Placencia_Peninsula_Stann_Creek.html"
    },
    {
      "name": "Jon",
      "location": "Verified Traveler",
      "rating": 5,
      "text": "We had Zane as our guide on the Monkey Rivers tour, he was excellent, how he spotted some of the wildlife hidden in the undergrowth I don't know.He took us to see - Manatee, Howler Monkeys, Turtles, Crocodiles, King Fishers and Iguanas.,It was a brilliant day out, HIGHLY RECOMMENDED 🥳🥳🥳🥳",
      "tour": "BEST RIVER MANGROVE TOUR",
      "link": "https://www.tripadvisor.com/Attraction_Review-g291977-d25566275-Reviews-Wilder_Belize_Adventures-Placencia_Placencia_Peninsula_Stann_Creek.html"
    }
  ],
  "faqs": [
    {
      "q": "How do I book a tour, and how far in advance should I do it?",
      "a": "Book right here on the site or message us directly, and we'll confirm by email within a day. High-season trips (December to April) and border crossings like Tikal fill up fast, so we recommend booking at least a week ahead, though we'll always try to fit you in on shorter notice."
    },
    {
      "q": "What should I bring on a tour?",
      "a": "Closed-toe shoes or hiking sandals, quick-dry clothes, a swimsuit under your clothes, reef-safe sunscreen, insect repellent, a hat, and a refillable water bottle. We provide the specialized gear (ATVs, helmets, cave equipment, life vests), and we'll send a tour-specific packing list when you book."
    },
    {
      "q": "How big are the groups?",
      "a": "We keep groups small on purpose, usually 2 to 10 guests, so your guide has time for you. If you'd prefer a fully private trip for your family or friends, just ask and we'll arrange it."
    },
    {
      "q": "Do you offer pickup and transfers?",
      "a": "Yes. Most tours include complimentary pickup and drop-off at hotels and resorts in and around Placencia Village. For trips that start farther afield, we'll arrange transport and tell you the meeting time when we confirm your booking."
    },
    {
      "q": "What happens if it rains?",
      "a": "Belize is a rainforest, so a passing shower is part of the adventure and most tours run rain or shine. If conditions become genuinely unsafe (lightning, flooding, rough seas), we'll reschedule you, switch you to another tour, or issue a full refund. Your guide always makes the safety call."
    },
    {
      "q": "How fit do I need to be?",
      "a": "It depends on the tour. River trips and Maya ruin visits are easy and family-friendly, while the Cockscomb hikes and ATM cave are moderate to challenging with climbing, wading, and uneven terrain. Each tour page lists a difficulty rating, and we're happy to help you pick one that fits your group."
    },
    {
      "q": "Are your tours suitable for kids?",
      "a": "Many are. Monkey River, the Maya ruins, and gentle waterfall trips are great for families with children, while ATM cave and some ATV routes have age and height minimums for safety. Tell us your kids' ages and we'll point you to the right adventures."
    },
    {
      "q": "What's your cancellation policy?",
      "a": "Cancel at least 48 hours before your tour for a full refund of your deposit. Inside 48 hours we can usually reschedule you to another date, and weather cancellations on our end are always refunded in full or rebooked at no cost."
    }
  ],
  "travelersInfo": [
    {
      "title": "Getting to Placencia",
      "body": "Most travelers fly into Philip S. W. Goldson International Airport (BZE) near Belize City, then reach Placencia by a short domestic flight to Placencia Airstrip (PLJ), a scenic shuttle, or a rental car down the Southern Highways (about a 3-hour drive). We can arrange a transfer for any of these routes so you land and relax."
    },
    {
      "title": "Best Time to Visit",
      "body": "The dry season from late November through April brings the sunniest skies and is peak time for jungle, reef, and ruin trips. The green season (June to November) is lush, quieter, and often cheaper, with warm afternoon showers and the most vibrant rainforest. Tours run year-round, and we'll steer you toward the best options for your dates."
    },
    {
      "title": "What to Pack",
      "body": "Light, quick-dry clothing, closed-toe shoes for hikes and caves, a swimsuit, reef-safe sunscreen, strong insect repellent, a hat, sunglasses, and a dry bag for electronics. Bring a light rain layer in green season and any personal medications, since pharmacies in the village are small."
    },
    {
      "title": "Health & Safety",
      "body": "No vaccinations are required for most visitors, but bug protection matters in the jungle, and tap water is best avoided in favor of bottled or filtered. Our guides are trained in wilderness first aid and carry first-aid kits and communication gear on every trip. Travel insurance that covers adventure activities is always a smart idea."
    },
    {
      "title": "Currency & Tipping",
      "body": "The Belize dollar is fixed at 2 BZD to 1 USD, and US dollars are accepted almost everywhere, so there's no need to exchange in advance. Cards work at larger businesses but carry cash for smaller vendors and village markets. Tipping your guide is customary and appreciated, with 10 to 15 percent a good benchmark for a great day out."
    },
    {
      "title": "Booking & Deposits",
      "body": "We hold your spot with a deposit at the time of booking, with the balance due on the day of your tour in cash or by card. You'll get a confirmation email with your meeting details, packing list, and guide's name. Questions before you arrive? Message us anytime and a real person in Placencia will answer."
    }
  ],
  "transfer": {
    "title": "Transfers & Ground Transport",
    "description": "Skip the guesswork of getting around southern Belize and let us drive. Our drivers know every turn of the Coastal plane and Southern Highways to Placencia, and our air-conditioned vehicles get you door to door so your adventure starts the moment you arrive.",
    "slideshowImages": [
      "/images/transfer-1.jpeg",
      "/images/transfer-2.jpeg",
      "/images/transfer-3.jpeg",
      "/images/transfer-4.jpeg"
    ],
    "routes": [
      {
        "from": "Belize City (BZE Airport)",
        "to": "Placencia",
        "price": 250,
        "duration": "approx. 3 hours"
      },
      {
        "from": "Placencia",
        "to": "Belize City (BZE Airport)",
        "price": 250,
        "duration": "approx. 3 hours"
      },
      {
        "from": "Hopkins / Dangriga",
        "to": "Placencia",
        "price": 120,
        "duration": "approx. 1.5 hours"
      },
      {
        "from": "Placencia",
        "to": "Hopkins / Dangriga",
        "price": 120,
        "duration": "approx. 1.5 hours"
      },
      {
        "from": "Placencia Airstrip (PLJ)",
        "to": "Placencia Village Hotels",
        "price": 25,
        "duration": "approx. 15 minutes"
      },
      {
        "from": "Placencia",
        "to": "Maya Beach / Seine Bight",
        "price": 35,
        "duration": "approx. 25 minutes"
      }
    ],
    "included": [
    
    ]
  },
  "newsletterPitch": "Sign up for the Wilder newsletter and get insider Belize travel tips, seasonal trip ideas, and first dibs on new adventures and deals."
} as const;
export const company = site.company;
